version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4567:4567'
    environment:
      PRISMA_CONFIG: |
        port: 4567
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~

# start prisma & db docker
# $ sytemctl start docker
# $ sudo docker-compose -f prisma/docker-compose.yml up -d
# initial configure prisma
# 
# $ prisma deploy
# $ prisma generate