version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            rawAccess: true
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~

# start prisma & db docker
# $ sytemctl start docker
# $ sudo docker-compose -f prisma/docker-compose.yml up -d
# initial configure prisma
# $ prisma init prisma --endpoint http://localhost:4466
# $ export PRISMA_MANAGEMENT_API_SECRET="2$D%7&^l;x.#{/@!"
# $ prisma deploy
# $ prisma generate
