name: Deploy Staging

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      SSH_PASS: ${{ secrets.SSH_PASS }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: sudo apt-get install sshpass
      - run: 
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no dev@167.179.102.140
          cd the-gig-atlas && git pull origin develop
          npm run bootstrap && npm run common:build
          cp server/.env.staging server/.env
          npm run server:prisma
          cp client/.env.staging client/.env && npm run client:build
          pm2 restart client && pm2 restart server
    