name: Deploy Staging

on:
  push: 
    branches: 
      - develop
  pull_request:
    branches:
      - develop


jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      SSH_PASS: ${{ secrets.SSH_PASS }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: sudo apt-get install sshpass
      - run: .scripts/./deploy-staging.sh 